app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

models:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /models
    options:
        expose: true
