# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig.extension.loader:
        class:        Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }
    app.twig_extension:
        class: AppBundle\Twig\ModelExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"