app_modelentity:
    resource: "@AppBundle/Resources/config/routing/modelentity.yml"
    prefix:   /modelentity

models_popup:
    path:     /ModelsPopup
    defaults: { _controller: AppBundle:Models:ModelsPopup }
    options:
        expose: true

list:
    path:     /list
    defaults: { _controller: AppBundle:Model:list }

show:
    path:     /show
    defaults: { _controller: AppBundle:Model:show }
